### ISSUE TITLE
Name of team

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Platform_Of_Corporate_Information_Systems#1]
Post and vote here your idea for name of team

**Comment by iamprovidence** [comment]
Some ideas:
|Latin|English|
|----|----|
|Corvinus |Raven|
|NAVI|Born to win|

**Comment by Lenkelheit** [comment]
I think "The demon of .Net" is a good one.

**Comment by Lenkelheit** [comment]
And demon is also translated as a good genius)

**Comment by Lenkelheit** [comment]
@iamprovidence No, to my mind, it sounds very simply and ineffective.

**Comment by vasil98** [comment]
For me, any meaningful command name is appropriate
