### ISSUE TITLE
Let's divide the tasks

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Platform_Of_Corporate_Information_Systems#10]
Describe what will you do, how will you do it, all types, all return types, all names, etc

I will heart :heart: you if you done all correctly

**Comment by SvyatoslavFedynyak** [comment]
All shape classes with double coordinates and other fields, all methods(with ishape realisation but without ifileManager realisation(dont remember how it should be done))
Sorting algorithms for shapes(quicksort maybe)

**Comment by iamprovidence** [comment]
what do you mean by "double coordinates"? what methods will be there?

**Comment by SvyatoslavFedynyak** [comment]
not int but double numbers
constructors, convert data to string, what else?

**Comment by iamprovidence** [comment]
double numbers? is coordinate double type? no! It's a Point, you probably will need additional struct to represent coordinate

**Comment by SvyatoslavFedynyak** [comment]
1 more struct? trust me its a bad idea
its good when you have more than 5-6 fields, but not 2-3

**Comment by SvyatoslavFedynyak** [comment]
or maybe if you want to do some manipulations with points out of shapes

**Comment by iamprovidence** [comment]
Create struct, today you just need x,y tommorrow additional methods, the nature of coordinate will never change, while x and y will do, point struct is much better to read than x1, x2, y1, y2

**Comment by iamprovidence** [comment]
Also you forgot to set your deadline day, and remember you should do not only classes but also unit-tests for all methods

**Comment by SvyatoslavFedynyak** [comment]
ok, ill do it like that
anything else?

**Comment by Lenkelheit** [comment]
I take work with IFileManager and realization it in classes. My deadline 06.09.2018.
Also I cover this with unit tests. Tomorrow I will tell you about all names that I will use.

**Comment by Lenkelheit** [comment]
@SvyatoslavFedynyak I think it is better to use for one task classic sorting and for other - Linq, so we will use almost all tasks from our technical project.

**Comment by SvyatoslavFedynyak** [comment]
My deadline is 09.09.2018, but I'm sure I'll do it earlier
I'll do:
Point
{
double x
double y
Point(doule x, double y)
static double Distance(Point A, point B)
}

**Comment by vasil98** [comment]
I will cover all the second part until 10th or 11th. also i mention that i need to know quarters for each shapes, would be nicer if you implemented that properties in IShape.

**Comment by Lenkelheit** [comment]
My deadline is 07.09.2018, but I think I'll do it today.
I'll do:
interface IFileManager
    {
        bool WriteToFile(string nameOfFile);
        bool ReadFromFile(string nameOfFile);
    }

**Comment by iamprovidence** [comment]
@Lenkelheit  do you really thing passing file names is good idea?

**Comment by Lenkelheit** [comment]
@iamprovidence I think that users will want to choose where they want to write to or read from.

**Comment by Lenkelheit** [comment]
@iamprovidence But how developer will do it, users will use it. I understand, thanks.

**Comment by SvyatoslavFedynyak** [comment]
Doesn't triangle need any realisation and fields, does it?

**Comment by iamprovidence** [comment]
@SvyatoslavFedynyak, 3 Point will be enought. there are some methods like "MiddlePoint", you will probably need there some fields
