### ISSUE TITLE
Bug Fixing

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Platform_Of_Corporate_Information_Systems#121]

**Comment by iamprovidence** [comment]
3. FOUND IT
it happens when time is over, but order is still executing
one thread makes SelectedOrder = null
while another try    orders.Remove(selectedOrder);
so you have unhandeled NullReferenceException

**Comment by iamprovidence** [comment]
3. FIX IT

**Comment by Lenkelheit** [comment]
> 1. FOUND IT
>    it happens when time is over, but order is still executing
>    one thread makes SelectedOrder = null
>    while another try    orders.Remove(selectedOrder);
>    so you have unhandled NullReferenceException

you don`t check in Remove if selectedOrder is null? and than do something

**Comment by iamprovidence** [comment]
@Lenkelheit , yeah. that what I have done

**Comment by Lenkelheit** [comment]
1. There is a problem when you sign up as one name, for example Nazar, and then log in with the same name but smaller letters, for example, Naza. I will fix it.

**Comment by iamprovidence** [comment]
@Lenkelheit , ok. I put it on you

**Comment by Lenkelheit** [comment]
> 1. There is a problem when you sign up as one name, for example Nazar, and then log in with the same name but smaller letters, for example, Naza. I will fix it.

FIXED
