### ISSUE TITLE
Writing and reading files

### ISSUE THREAD

**Issue by Lenkelheit** [iamprovidence/Platform_Of_Corporate_Information_Systems#13]
Is it better to read and write to special standart file or to do it to file which I want to choose? How do you think?

**Comment by Lenkelheit** [comment]
So need I use arguments of name of file or without it?

**Comment by iamprovidence** [comment]
it not your bisness, you just need to provide tools, the user should worry about how to use them

**Comment by Lenkelheit** [comment]
Ok, let it be.

**Comment by iamprovidence** [comment]
i think file name as arguments is wrong idea, every instance of class should read adn write to file, but how user will work with a lot of instances? he would passes file name to each? and you will every time open/write/close file? seems bad. you probably need to try pass Stream or something like that

**Comment by iamprovidence** [comment]
also with writing methods filename argumnts will work, but for reading it certainly will not

**Comment by Lenkelheit** [comment]
ok, thanks

**Comment by Lenkelheit** [comment]
If file doesn`t exist, it will be created, I think

**Comment by iamprovidence** [comment]
about which method you a talk right now?

**Comment by Lenkelheit** [comment]
@iamprovidence  Or what do you mean?

**Comment by Lenkelheit** [comment]
about ReadFromFile

**Comment by Lenkelheit** [comment]
stop

**Comment by iamprovidence** [comment]
ok, you will have WriteToFile that takes file name, but how would you ReadToFile that takes file name work?

**Comment by iamprovidence** [comment]
that's right. no way(at least I don't see valid one).

so you can create WriteToFile(file name) and  ReadToFile(stream). but it does not seem right either. This methods describe the same work process, so they should work and look same. 

In the best way this implementation will look like

-  WriteToFile(stream) 
- ReadToFile(stream)

**Comment by Lenkelheit** [comment]
Thanks, I will do it like you say.
