### ISSUE TITLE
Coding Convention

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Platform_Of_Corporate_Information_Systems#3]
Let's set Coding Convention for the whole repository

**Comment by iamprovidence** [comment]
I support all convention that we covered at lection, and propose some addition:
use short name for GUI: cancleButton -> cancelBtn
use separator with GUI events: cancelBtn_eventClick(...)
variables name for exception in catch block: *ex*

**Comment by Lenkelheit** [comment]
Need we use _e_ or _ex_ for catch blocks? Or you mean _e_ is for variables name of some events, so we use for exception _ex_?
We really need write //FIELDS before them? It will be a lot of comments in code.

**Comment by Lenkelheit** [comment]
Need we to all fields and methods write such comments? Oh my .....

**Comment by iamprovidence** [comment]
for catch block we should use *ex*, for events *e* to avoid syntax errors, especially if you a trying to cath exception in some event

I do think we need // FIELDS, and other section comments, for big classes, you read code more often than write, and in this way we will improve readability

And I do not get you last comments. Can you explain what bother you?

**Comment by iamprovidence** [comment]
why not?

**Comment by Lenkelheit** [comment]
Need we sign that it is field with comment // FIELD? And, in such way, for methods?

**Comment by Lenkelheit** [comment]
Because... hmmm...Do you want to see more comments than real code like a lot of big companies do?

**Comment by Lenkelheit** [comment]
I think it will be too many comments.

**Comment by iamprovidence** [comment]
it a single comment line that splits code section for structuring the code and improving readability.

**Comment by iamprovidence** [comment]
it shall be too many comments

**Comment by Lenkelheit** [comment]
Can you expain me again? I don`t understand about what you.

**Comment by iamprovidence** [comment]
why are you so worried aboud comments? as I said previously "you read code more often than write". There should be lot's of comments. There is nothing bad in comments

**Comment by Lenkelheit** [comment]
Ok, I agree.
