### ISSUE TITLE
File hierarchy

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Platform_Of_Corporate_Information_Systems#4]
Let's set File Hierarchy to every task

**Comment by iamprovidence** [comment]
My propose:
unit test and main project in one solution but in different projects
each project has the "Models" folder with inners folder
- Classes
- Interfaces
- EventArgClasses
- ExtensionClasses
- Forms
- User controls
- etc
Folders depends on project

**Comment by Lenkelheit** [comment]
What folders need we use in unit tests? Or none?

**Comment by Lenkelheit** [comment]
Ok, it is good.
