### ISSUE TITLE
Let's organize team work

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Platform_Of_Corporate_Information_Systems#6]
Here we organize how our work process. We can set a leader for pass outing tasks, we can divide tasks by processes like unit test, xml doc so on and share them, we can change work per task, your suggestions

**Comment by iamprovidence** [comment]
In my opiniong, after a new task become available we should divide it on several tasks and everybody get his own pointing out a deadline for his work. In this case one should do unit test and documentation to his part of work

**Comment by SvyatoslavFedynyak** [comment]
I think we should disribute roles like: 2 guys for coding, 1 for unit tests and XML documentation and 1 for github advancement.

**Comment by iamprovidence** [comment]
I see no reason to duty a separate person on XML documentation, still if you are writing a code, you know what it does (i mean code), so you shoud document it. It same as comments, you write comments to your code, you should also wrire XML comments.
If we would have a separate person on XML documentation it means that one person should read all code, understand it and comment it. That would waste lot's of time. Seems worthless for me.
