### ISSUE TITLE
Distribute profession

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Platform_Of_Corporate_Information_Systems#7]
Let's distribute some profession for repository administration:

|Work|Profession Name|
|-----|-----|
|Answering Questions||
|Bug reports||
|Blogposts|Bloger|
|Code|Coder|
|Documentation||
|Design|Designer|
| Ideas & Planning||
| Infrastructure (Hosting, Build-Tools, etc)||
| Reviewed Pull Requests||
| Tests|Tester|
|Text Validation||

and yeah, they also need names

**Comment by iamprovidence** [comment]
I mean while, I already have done a great part of work in Blogpost, Documentaion and Design this profession belong to me

**Comment by Lenkelheit** [comment]
In design? Where is it?

**Comment by iamprovidence** [comment]
diagram design
