### ISSUE TITLE
Let us write a user story

### ISSUE THREAD

**Issue by iamprovidence** [iamprovidence/Platform_Of_Corporate_Information_Systems#88]
It should be a "taxi order" for taxi driver

**Comment by iamprovidence** [comment]
**program launch up**
when you launch a program you need to sign up or log in.
**as a user, I want...**
... to have a list of all orders. When I click on a certain order the full information on it has been shown.
Every order should have 'time to done' and give me a money. Each task brings me money and take some time to fulfill. While task has been operating, I can not do anuthing, only refuse from task but if so I will be fined. I can search for new task (will take some time) or refuse from some orders immediately. The orders however can run out time itselves.
My workday continues for some times and after time has been left all the information about my work has been saved. All the previous information can be seen by me.
My task is to earn as much money as i can.
Also I want to have a way to log out and exit, or log in by other name.

**Comment by Lenkelheit** [comment]
> Each task brings me money and take some time to fulfill.

All this in real time?

**Comment by Lenkelheit** [comment]
> I can search for new task (will take some time) or refuse from some orders immediately.

Refuse without fine, yes?

**Comment by Lenkelheit** [comment]
> My workday continues for some times and after time has been left all the information about my work has been saved.

And you will be automatically logged out, program will be closed by itself or something else?

**Comment by iamprovidence** [comment]
@Lenkelheit yes

**Comment by iamprovidence** [comment]
@Lenkelheit yes, because its only hiding orders

**Comment by iamprovidence** [comment]
@Lenkelheit hmmm, I dont know, lets think. What the best way you see here?

**Comment by Lenkelheit** [comment]
> hmmm, I dont know, lets think. What the best way you see here?

Maybe sets a timer on the all screen to next workday?

**Comment by Lenkelheit** [comment]
> While task has been operating

You can log out and what wil be with time? Will be running or stop?

**Comment by iamprovidence** [comment]
@Lenkelheit you are right. There is could be a button "start"

**Comment by Lenkelheit** [comment]
> you are right. There is could be a button "start"

When do you close program?

**Comment by Lenkelheit** [comment]
And when you close program time must be stopped?

**Comment by Lenkelheit** [comment]
And next time will time be continued?

**Comment by Lenkelheit** [comment]
And one more,

> I can search for new task (will take some time)

All tasks will be the same or quite different?

**Comment by iamprovidence** [comment]
No, no, no. When you start a program you need log in, if you whant to play you should press "start", when you close the program there will be nothing. Only when you run out time, there will be a message "thanks for pkaying" and all the scores will be saved

**Comment by iamprovidence** [comment]
"Continue" and so on, will be too complicated, I think

**Comment by Lenkelheit** [comment]
> In real life. I think 30 second will be enough

What about workday? How much time will it be running?

**Comment by iamprovidence** [comment]
30sec

**Comment by Lenkelheit** [comment]
> 30sec

Ok, so what about one task?

**Comment by iamprovidence** [comment]
2-5sec

**Comment by Lenkelheit** [comment]
> 2-5sec

Ok, it will be good.

**Comment by Lenkelheit** [comment]
What about time between workday? Or there will be button "start"?

**Comment by iamprovidence** [comment]
No timer between workday. Wanna play? Press "start", thats all

**Comment by Lenkelheit** [comment]
If time is over, will fine be when you have running task??

**Comment by iamprovidence** [comment]
:weary:

**Comment by iamprovidence** [comment]
No, there will be no fine

**Comment by iamprovidence** [comment]
> If time is over, will fine be when you have running task?

but you are right that think about this behavior, we should remember this, because it could became a bug in future

**Comment by Lenkelheit** [comment]
> And one more,
> 
> > I can search for new task (will take some time)
> 
> All tasks will be the same or a bit different?

What about that?

**Comment by iamprovidence** [comment]
@Lenkelheit , i think they all will be the same. Do you have any idea how different thay could be?

**Comment by Lenkelheit** [comment]
> @Lenkelheit , i think they all will be the same. Do you have any idea how different thay could be?

Maybe generate different streets, money and time. What about description of orders I don`t know.

**Comment by iamprovidence** [comment]
@Lenkelheit , there will be different streets, money amount and time. that for sure. Description is unnecessary, I think. but I dont see any difference between orders

**Comment by Lenkelheit** [comment]
> @Lenkelheit , there will be different streets, money amount and time. that for sure. Description is unnecessary, I think. but I dont see any difference between orders

I think it is enough.
